In [1]:
# For tips on running notebooks in Google Colab, see
# https://pytorch.org/tutorials/beginner/colab
%matplotlib inline


Tensors
=======




![imagem](https://drive.google.com/uc?id=1yu5MuPb6e_VPsJuCW0rX_URtZPXF1Vms)
Três atributos principais definem um tensor:

* **Rank (Ordem)**

* **Shape (Forma)**

* **Tipo de dado**

Aqui, a ordem de um tensor se refere ao número de eixos do tensor.

Exemplos:

A ordem de uma matriz é 2 porque ela possui dois eixos.

A ordem de um vetor é 1 porque ele possui um único eixo.

A forma de um tensor se refere ao número de dimensões ao longo de cada eixo.

Exemplo:

Uma matriz quadrada pode ter dimensões (2, 2).

Um tensor de ordem 3 pode ter dimensões (3, 5, 8).

O tipo de dado de um tensor se refere ao tipo de dados que ele contém.

Aqui estão alguns dos tipos de dados suportados:
* float32
* float64
* uint8
* int32
* int64


## Um escalar (tensor 0D)
Possui ordem 0 e contém um único número.


In [2]:
import numpy as np

tensor = np.array(42)
tensor.shape

()

In [3]:
tensor.ndim

0

## Um vetor (tensor 1D)
Possui ordem 1 e representa um array de números.


In [4]:
import numpy as np

tensor = np.array([8,16,32,64])
tensor.shape

(4,)

In [5]:
tensor.ndim

1

## Uma matriz (tensor 2D)
Possui ordem 2 e representa um array de vetores. Os dois eixos de uma matriz são geralmente chamados de linhas e colunas.


In [6]:
import numpy as np

tensor = np.array([[2,10,12,24],
                   [8,16,32,64],
                   [5,10,15,20]])
tensor.shape

(3, 4)

In [7]:
tensor.ndim

2

Aqui estão algumas representações comuns de tensores:

Vetores: 1D — (features)

Sequências: 2D — (timesteps, features)

Imagens: 3D — (altura, largura, canais)

Vídeos: 4D — (frames, altura, largura, canais)

Geralmente, os algoritmos de machine learning lidam com um subconjunto de dados por vez, chamado **batch**.

Ao usar um batch de dados, o primeiro eixo do tensor é reservado para o tamanho do batch (número de amostras).

Por exemplo, se você estiver lidando com tensores 2D (matrizes), um batch delas terá um total de 3 dimensões:

* (exemplos, linhas, colunas)

Observe que o primeiro eixo é o número de matrizes que temos no nosso batch.

Seguindo a mesma lógica, um batch de imagens pode ser representado como um tensor 4D:

* (exemplos, altura, largura, canais)

E um batch de vídeos como um tensor 5D:

* (exemplos, frames, altura, largura, canais)


In [8]:
import torch
import numpy as np

In [9]:

print("torch version:",torch.__version__)

torch version: 2.6.0+cu124


Initializing a Tensor
=====================
In PyTorch, we use tensors to encode the inputs and
outputs of a model, as well as the model's parameters.

Tensors are similar to [NumPy's](https://numpy.org/) ndarrays, except
that tensors can run on GPUs or other hardware accelerators. In fact,
tensors and NumPy arrays can often share the same underlying memory,
eliminating the need to copy data (see
`bridge-to-np-label`{.interpreted-text role="ref"}). Tensors are also
optimized for automatic differentiation (we\'ll see more about that
later in the [Autograd](autogradqs_tutorial.html) section). If you're
familiar with ndarrays, you'll be right at home with the Tensor API. If
not, follow along!


----
Tensors can be initialized in various ways. Take a look at the following
examples:

**Directly from data**

Tensors can be created directly from data. The data type is
automatically inferred.


In [10]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

**From a NumPy array**

Tensors can be created from NumPy arrays (and vice versa - see
`bridge-to-np-label`{.interpreted-text role="ref"}).


In [11]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

**From another tensor:**

The new tensor retains the properties (shape, datatype) of the argument
tensor, unless explicitly overridden.


In [12]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")
x_ones = torch.zeros_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Ones Tensor: 
 tensor([[0, 0],
        [0, 0]]) 

Random Tensor: 
 tensor([[0.5845, 0.8061],
        [0.3473, 0.0972]]) 



**With random or constant values:**

`shape` is a tuple of tensor dimensions. In the functions below, it
determines the dimensionality of the output tensor.


In [13]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
#zeros_tensor = torch.zeros(shape,dtype=torch.int)
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8544, 0.5697, 0.9979],
        [0.2388, 0.9922, 0.4096]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


------------------------------------------------------------------------


Attributes of a Tensor
======================

Tensor attributes describe their shape, datatype, and the device on
which they are stored.


In [14]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


------------------------------------------------------------------------


Operations on Tensors
=====================

Over 1200 tensor operations, including arithmetic, linear algebra,
matrix manipulation (transposing, indexing, slicing), sampling and more
are comprehensively described
[here](https://pytorch.org/docs/stable/torch.html).

Each of these operations can be run on the CPU and
[Accelerator](https://pytorch.org/docs/stable/torch.html#accelerators)
such as CUDA, MPS, MTIA, or XPU. If you're using Colab, allocate an
accelerator by going to Runtime \> Change runtime type \> GPU.

By default, tensors are created on the CPU. We need to explicitly move
tensors to the accelerator using `.to` method (after checking for
accelerator availability). Keep in mind that copying large tensors
across devices can be expensive in terms of time and memory!


In [30]:
tensor = tensor.to('cuda:0')
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [16]:
# We move our tensor to the current accelerator if available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

Try out some of the operations from the list. If you\'re familiar with
the NumPy API, you\'ll find the Tensor API a breeze to use.


**Standard numpy-like indexing and slicing:**


In [17]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Joining tensors** You can use `torch.cat` to concatenate a sequence of
tensors along a given dimension. See also
[torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html),
another tensor joining operator that is subtly different from
`torch.cat`.


In [18]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [19]:
t1.shape

torch.Size([4, 12])

In [20]:
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [21]:
t1.shape

torch.Size([12, 4])

**Arithmetic operations**


In [34]:
tensor.T

tensor([[18., 18., 18., 18.],
        [15., 15., 15., 15.],
        [18., 18., 18., 18.],
        [18., 18., 18., 18.]], device='cuda:0')

In [35]:
tensor

tensor([[18., 15., 18., 18.],
        [18., 15., 18., 18.],
        [18., 15., 18., 18.],
        [18., 15., 18., 18.]], device='cuda:0')

In [22]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

print(torch.allclose(y1, y2))

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

True


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

**Single-element tensors** If you have a one-element tensor, for example
by aggregating all values of a tensor into one value, you can convert it
to a Python numerical value using `item()`:


In [23]:
agg = tensor.sum()
print(agg)
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(12.)
12.0 <class 'float'>


**In-place operations** Operations that store the result into the
operand are called in-place. They are denoted by a `_` suffix. For
example: `x.copy_(y)`, `x.t_()`, will change `x`.


In [24]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [25]:
tensor.mul_(3)
print(tensor )

tensor([[18., 15., 18., 18.],
        [18., 15., 18., 18.],
        [18., 15., 18., 18.],
        [18., 15., 18., 18.]])


<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>

<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">

<p>In-place operations save some memory, but can be problematic when computing derivatives because of an immediate lossof history. Hence, their use is discouraged.</p>

</div>



------------------------------------------------------------------------


Bridge with NumPy {#bridge-to-np-label}
=================

Tensors on the CPU and NumPy arrays can share their underlying memory
locations, and changing one will change the other.


Tensor to NumPy array
=====================


In [26]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.


In [27]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


NumPy array to Tensor
=====================


In [28]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.


In [29]:
np.add(n, 1, out=n) #op no numpy
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
